### ISSUE TITLE
Webpage broken?

### ISSUE THREAD

**Issue by praiseskeltal** [sotnrando/sotnrando#20] opened 2019-05-25 14:23 UTC
# Seed URL
--

# Emulator and version:
--

# Bug description
Attempting to randomize via the sotn.io webpage crashes the tab on Firefox. Attempted with no tracker/cookie blocking activated. Also, website does not accept .cue files, contrary to what the "Help" section states.

# How to reproduce:
Insert track 1 .bin file to website, click randomize with any settings. *Edit: Using Firefox, untested with Chrome, etc.

**Comment by johnoliverdriscoll** [comment] 2019-05-25 15:58
What OS and version of FF are you using? Please provide a seed that causes a crash, even if you have to make one up.

As for the help section, it states this...

>  If your disc image is split across two .bin files, **drag only the first .bin file** (track 1) into the drop zone.

**Comment by 3snowp7im** [comment] 2019-05-25 16:03
What OS and version of FF are you using? Please provide a seed that causes a crash, even if you have to make one up.

As for the help section, it states this...

> If your disc image is split across two .bin files, **drag only the first .bin file** (track 1) into the drop zone.

**Comment by praiseskeltal** [comment] 2019-05-25 22:09
Currently Windows 10, Firefox version 67.0.
Seed: coolseedname

Seems I was mislead by the sentence right before originally.

**Comment by 3snowp7im** [comment] 2019-05-26 08:08
Do you have any extensions enabled? If so, have you tried disabling them?

**Comment by praiseskeltal** [comment] 2019-05-26 13:38
No extensions at all.

**Comment by 3snowp7im** [comment] 2019-05-29 05:27
Have tested in both Chrome and Firefox on Windows 10 and was unable to reproduce the crash. I wish I could help, but I can't fix what I can't reproduce. You may want to try through Chrome or Opera.

**Comment by Exustio** [comment] 2019-05-30 12:57
Having the same issues, also Windows 10 and Firefox 67.0. No extensions, any seed. I'm suspecting that Edge is doing the same, but not crashing the tab and instead perpetually loading. I've previously generated files using Firefox and the same image, nothing has changed.

**Comment by SmashManiac** [comment] 2019-06-30 02:09
treos has reported the same crash on the ROMHacking.net forums:
https://www.romhacking.net/forum/index.php?topic=22579.160

Maybe it's a 32-bit vs 64-bit issue?

**Comment by 3snowp7im** [comment] 2019-08-16 01:32
I think the issue may have been resolved by https://github.com/3snowp7im/SotN-Randomizer/commit/8372b4c1fa882ff40997003123014f86cba5f03a

If the crashing persists, please comment.

**Comment by 3snowp7im** [comment] 2019-08-20 07:02
Issue appears to be resolved.

**Closed as completed by 3snowp7im** 2019-08-20 07:02 UTC
Labels: Bug, Multi-Person
